Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-10, with the labels that each got.

#3782 SWATCH-2903 Marketplace throws vague error when handling Default api exception
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
Labels: QE Unneeded, Dev

#3688 SWATCH-2872: deploy kafka-bridge as resource
  deploy_ephemeral_env.sh
  deploy_kafka_bridge.sh
  kafka-bridge.yaml
  kafka-bridge/deploy/template.yaml
  pr_check.sh
Labels: QE Unneeded, Dev/approved

#3824 SWATCH-2958: Set billing producer aws when role is moa
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
  swatch-model-events/schemas/event.yaml
Labels: Dev/approved, QE/approved

#3813 SWATCH-2963: Count Splunk transmission failures in Quarkus apps
  .gitignore
  settings.gradle
  swatch-billable-usage/build.gradle
  swatch-common-splunk/build.gradle
  swatch-common-splunk/src/main/java/com/redhat/swatch/splunk/CountingSplunkErrorCallback.java
  swatch-contracts/build.gradle
  swatch-metrics/build.gradle
  swatch-producer-aws/build.gradle
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/splunk/QuarkusHecErrorCallback.java
  swatch-producer-azure/build.gradle
Labels: QE Unneeded, Dev/approved

#3819 SWATCH-2611: Update existing billable_usage_remittance status to unknown
  src/main/resources/liquibase/202410021300-update_usages_to_unknown.xml
  src/main/resources/liquibase/changelog.xml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
Labels: Dev/approved, QE/approved

#3832 SWATCH-3006: Support back uom in the events ingestion
  src/main/java/org/candlepin/subscriptions/event/EventNormalizer.java
  swatch-model-events/schemas/event.yaml
Labels: Dev, QE/approved

#3821 SWATCH-2915 Specify BYOS aws product code
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Labels: Dev/approved, QE/approved

#3822 SWATCH-2995 Retry billable usage when it gets marketplace retry error
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsThrottlingException.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/ErrorCode.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
Labels: Dev/approved, QE/approved

#3827 SWATCH-2993: Remove prune subscriptions API
  README.md
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
  docs/kafka-topics.md
  src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionPruneController.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionPruneListener.java
  src/main/resources/application-capacity-ingress.yaml
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionPruneControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/tasks/EnabledOrgsMessageConsumerTest.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/Channels.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/EnabledOrgsProducer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionPruneTaskConsumer.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/EnabledOrgsProducerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/InMemoryMessageBrokerKafkaResource.java
  swatch-subscription-sync/README.md
  swatch-subscription-sync/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3838 SWATCH-3007: Remove uom usage in the EventNormalizer and EventController classes
  src/main/java/org/candlepin/subscriptions/event/EventNormalizer.java
  swatch-model-events/schemas/event.yaml
Labels: QE Unneeded, Dev/approved

#3825 SWATCH-3018 Create a swatch-unleash-importer clowdapp
  .unleash/flags.json
  bin/build-images.sh
  deploy/rhsm-clowdapp.yaml
  deploy/unleash-import-clowdapp.yaml
  swatch-unleash-import/Dockerfile
  swatch-unleash-import/README.md
Labels: QE Unneeded, Dev/approved

#3848 SWATCH-3026: Create RbacApi and RbacService into the Quarkus Rbac Client
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApi.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiException.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiFactory.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiImpl.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacClient.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacService.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/StubRbacApi.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/rbac/RbacApiConfigurationUsingStubsTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/RbacUseStubService.java
Labels: QE Unneeded, Dev

#3861 Hotfix aws throttling and retry issue
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsThrottlingException.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/ErrorCode.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: Dev/approved

#3850 SWATCH-2990: Build swatch-metrics-hbi in Konflux on hotfix branch
  .tekton/swatch-metrics-hbi-pull-request.yaml
  .tekton/swatch-metrics-hbi-push.yaml
Labels: Dev/approved

#3867 Improve billable usage logging to include full aggregate object
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
Labels: QE Unneeded, Dev/approved

#3872 SWATCH-3036: Use separated transactions when processing retry remittance
  src/main/resources/liquibase/202410211200-retry-after-billable-usage-index.xml
  src/main/resources/liquibase/changelog.xml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/configuration/ApplicationConfiguration.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
Labels: QE, Dev/approved

#3834 SWATCH-2951: Allow to filter by metrics in the Instances Table API
  src/main/java/org/candlepin/subscriptions/resource/api/v1/InstancesResource.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
  src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/InstancesResourceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceNonPaygView.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstancePaygView.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstancesDbReportCriteria.java
Labels: Dev/approved, QE/approved

#3879 SWATCH-3036: Fix pagination to process remittances retries
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
Labels: Dev/approved, QE/approved

#3855 Fix `gradlew tasks`
  buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
  buildSrc/src/main/groovy/swatch.spring-boot-rest-client-conventions.gradle
Labels: Dev/approved

#3862 SWATCH-2899: Subscription type is On-demand for Paygo products
  src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableController.java
  src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableControllerTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1Test.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/ProductId.java
Labels: Dev/approved, QE/approved

#3887 Set existing retryable remittances to failed
  src/main/resources/liquibase/202410241408-clear-retryable.xml
  src/main/resources/liquibase/changelog.xml
Labels: QE, Dev/approved

#3883 SWATCH-3041: Populate traceresponse header in spring boot services
  swatch-core/build.gradle
  swatch-core/src/main/java/org/candlepin/subscriptions/resteasy/TraceResponseFilter.java
  swatch-core/src/test/java/org/candlepin/subscriptions/resteasy/TraceResponseFilterTest.java
Labels: Dev/approved, QE/approved

#3894 SWATCH-3053: Bump Gradle from 8.3 to 8.5
  gradle/wrapper/gradle-wrapper.properties
  swatch-contracts/gradle/wrapper/gradle-wrapper.jar
  swatch-contracts/gradle/wrapper/gradle-wrapper.properties
Labels: QE Unneeded, Dev

#3859 SWATCH-718: Ensure SnakeYAML does not deserialize arbitrary classes
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistry.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
  swatch-product-configuration/src/test/resources/cve_2022_1471_product.yaml
  swatch-product-configuration/src/test/resources/cve_2022_1471_swatch_config_index.txt
Labels: QE Unneeded, Dev/approved

#3888 SWATCH-2297: Add a metric for ingested usage data from Prometheus
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
Labels: Dev/approved, QE/approved

#3866 SWATCH-3034: Fix the Quarkus AccessApi generated client interface
  CONTRIBUTING.md
  clients/rbac-client/rbac-api-spec.yaml
Labels: QE Unneeded, Dev
