Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-03, with the labels that each got.

#3055 SWATCH-2144: Populate cloud provider instance IDs from HBI when possible
  src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
  src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
  src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
  src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
  src/test/java/org/candlepin/subscriptions/inventory/db/InventoryRepositoryIT.java
Labels: QE

#3122 Print logs after bad requests in Quarkus services
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.yaml
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded

#3030 SWATCH-1220: Script to perform live reloads in the ephemeral environments
  Dockerfile
  bin/build-images.sh
  poetry.lock
  pyproject.toml
  swatch-api/deploy/clowdapp.yaml
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-system-conduit/Dockerfile
  swatch-system-conduit/deploy/clowdapp.yaml
  swatchdog/Makefile
  swatchdog/README.md
  swatchdog/setup.cfg
  swatchdog/swatchdog/__init__.py
  swatchdog/swatchdog/cli.py
  swatchdog/swatchdog/deploy/__init__.py
  swatchdog/swatchdog/deploy/command.py
  swatchdog/tests/__init__.py
Labels: QE Unneeded

#3119 SWATCH-2246: Echo CA information used by JDBC to the console on start-up
  swatch-core/src/main/java/org/candlepin/subscriptions/actuator/CertInfoInquisitor.java
  swatch-core/src/main/java/org/candlepin/subscriptions/clowder/RdsSslBeanPostProcessor.java
  swatch-core/src/main/java/org/candlepin/subscriptions/clowder/X509PemReader.java
  swatch-core/src/test/java/org/candlepin/subscriptions/actuator/CertInfoInquisitorTest.java
  swatch-core/src/test/java/org/candlepin/subscriptions/clowder/X509PemReaderTest.java
  swatch-core/src/test/resources/ca-bundle-no-newline.pem
  swatch-core/src/test/resources/ca-bundle.p12
  swatch-core/src/test/resources/ca-bundle.pem
Labels: QE Unneeded

#3126 SWATCH-2214 Switch from RateLimiter to BulkLimiter when calling RSHM API
  clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmService.java
  swatch-system-conduit/src/main/resources/application.yaml
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/rhsm/RhsmServiceTest.java
Labels: QE Unneeded

#3065 SWATCH-1937: Refactor contract ingestion to increase consistency
  swatch-contracts/README.md
  swatch-contracts/build.gradle
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractDtoMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/PartnerEntitlementsRequest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/AwsPartnerEntitlementsProvider.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/AzurePartnerEntitlementsProvider.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/BasePartnerEntitlementsProvider.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/utils/ContractMessageProcessingResult.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/SubscriptionEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Labels: Dev/approved, QE/approved

#3133 Document PR labels
  CONTRIBUTING.md
Labels: Dev/approved, QE/approved

#2821 SWATCH-1917: Set cores/sockets to null when value is not present
  src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
  src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/main/resources/liquibase/202311211112-remove-default-sockets-cores-on-buckets.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/db/HostTallyBucketRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
  src/test/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollectorTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
Labels: Dev/approved, QE/approved

#3125 SWATCH-1896: exclude RHEL rhel ELS/HA/RS from OpenShift and Satellite
  src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/main/resources/product-stub-data/engprods-SKU00790.json
  src/main/resources/product-stub-data/tree-SKU00790_attrs-true.json
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift_Container_Platform.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/Satellite_Capsule.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/Satellite_Server.yaml
Labels: Dev/approved, QE/approved

#3136 SWATCH-2214: Synchronize orgs in conduit using tasks
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitProperties.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
  swatch-system-conduit/src/main/resources/application.yaml
  swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResourceTest.java
Labels: Dev/approved, QE/approved

#3144 SWATCH-2214: Replace bulkhead.releasePermission by onComplete
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmService.java
Labels: QE Unneeded

#3137 SWATCH-2026: Add a grafana dashboard for export requests
  .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
Labels: QE Unneeded, Dev/approved

#3148 SWATCH-1386: Add metric_id to openapi definitions
  api/rhsm-subscriptions-api-spec.yaml
  src/main/java/org/candlepin/subscriptions/capacity/admin/MetricMapper.java
  src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
  src/main/java/org/candlepin/subscriptions/resource/SubscriptionResource.java
  src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
  src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapper.java
  src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
  src/main/spec/internal-subscriptions-sync-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
  src/test/java/org/candlepin/subscriptions/resource/SubscriptionResourceTest.java
  src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapperTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-core/schemas/tally_snapshot.yaml
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
  swatch-model-events/schemas/event.yaml
Labels: Dev/approved, QE/approved

#3156 SWATCH-2329 Replace the deprecated methods in KafkaProperties
  src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/product/OfferingWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaConfigurator.java
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/InventoryServiceKafkaConfigurator.java
Labels: QE Unneeded, Dev/approved

#3157 Add billing provider to filterable parameters for subscription resource
  src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
Labels: Dev, Dev/approved, QE/approved

#3139 Replace hardcoded list of bonfire components in pr_check.sh
  pr_check.sh
Labels: QE Unneeded, Dev

#3153 SWATCH-2286: Change Billable Usage Remittance PK to UUID
  .github/workflows/validate-floorplan-queries.yaml
  docker-compose.yml
  src/main/java/org/candlepin/subscriptions/retention/RemittanceRetentionController.java
  src/main/java/org/candlepin/subscriptions/tally/AccountResetService.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
  src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
  src/main/resources/liquibase/202403131500-change-pk-from-billable-usage-remittance.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/retention/RemittanceRetentionControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapperTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
  swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
  swatch-core/schemas/billable_usage.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceFilter.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntityPK.java
Labels: QE, Dev/approved, QE/approved

#3165 SWATCH-2021: Move export related classes into the same package
  src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
  src/main/java/org/candlepin/subscriptions/capacity/CapacityIngressConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/export/ExportClientConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionListener.java
  src/main/resources/application.yaml
  src/test/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionListenerTest.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithExportServiceWireMock.java
Labels: QE Unneeded, Dev/approved

#3154 swatch-1382 add metric_id to tally_summary kafka messages
  swatch-core/schemas/tally_snapshot.yaml
Labels: Dev/approved, QE/approved

#3162 SWATCH-2330: Reduce the number of queries to purge the tally snapshots
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
  src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Labels: Dev/approved, QE/approved

#3187 SWATCH-2366: Unify resteasy dependencies into one single property
  dependencies.gradle
Labels: QE Unneeded

#3179 Hot reload Quarkus code in ephemeral environments
  Dockerfile
  bin/build-images.sh
  bin/dev-argfile.conf
  poetry.lock
  pyproject.toml
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics/deploy/clowdapp.yaml
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/deploy/clowdapp.yaml
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/deploy/clowdapp.yaml
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/resources/application.properties
  swatch-system-conduit/Dockerfile
  swatch-system-conduit/deploy/clowdapp.yaml
  swatchdog/README.md
  swatchdog/swatchdog/__init__.py
  swatchdog/swatchdog/deploy/command.py
Labels: QE Unneeded, Dev/approved

#3167 SWATCH-2345: Remove stale host buckets during hourly tally
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/resources/product-stub-data/engprods-MW02164HR.json
  src/main/resources/product-stub-data/tree-MW02164HR_attrs-true.json
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Labels: Dev/approved, QE/approved

#3181 [HOTFIX] SWATCH-2345: Remove stale host buckets during hourly tally
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/resources/product-stub-data/engprods-MW02164HR.json
  src/main/resources/product-stub-data/tree-MW02164HR_attrs-true.json
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Labels: Dev/approved, QE/approved

#3177 SWATCH-2276: Expose the OrgConfigRepository.findSyncEnabledOrgs
  src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/tasks/EnabledOrgsMessageConsumer.java
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/tally/tasks/EnabledOrgsMessageConsumerTest.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
  swatch-core/schemas/enabled_orgs_request.yaml
  swatch-core/schemas/enabled_orgs_response.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3198 SWATCH-2387: Update tag on postgresql-12-centos7 database
  .github/workflows/validate-floorplan-queries.yaml
  docker-compose.yml
  swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
Labels: QE Unneeded, Dev/approved

#3188 SWATCH-2326: include the inventory_id in the instances report
  api/rhsm-subscriptions-api-spec.yaml
  src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
  src/main/resources/liquibase/202403260830-update-instance-view-to-include-inventory-id.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
Labels: Dev/approved, QE/approved
