Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-05, with the labels that each got.

#3312 Update unit test for first day of month failure
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
Labels: QE Unneeded, Dev/approved

#3308 Configure logging SQL queries by deployment property
  swatch-api/deploy/clowdapp.yaml
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/resources/application.properties
  swatch-core/src/main/resources/swatch-core/application.yaml
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3277 SWATCH-2356: Send request to enabled-orgs-for-tasks for prune and sync
  swatch-contracts/build.gradle
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/ApplicationConfiguration.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/EnabledOrgsProducer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionPruneTaskConsumer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncTaskConsumer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/json/EnabledOrgsResponseDeserializer.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsTestingResourceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/EnabledOrgsProducerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionPruneTaskConsumerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncTaskConsumerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/InMemoryMessageBrokerKafkaResource.java
Labels: Dev/approved, QE/approved

#3291 SWATCH-2465: Do not filter by metric if not set in the Instances API
  src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesJsonDataMapperService.java
  src/main/resources/liquibase/202404240830-update-instance-view-to-aggregate-metrics.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core-test/src/main/resources/application-test.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/RhsmSubscriptionsDataSourceConfiguration.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceViewKey.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/converters/EventRecordConverter.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/converters/TallyInstanceViewMetricsConverter.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java
Labels: QE, Dev/approved

#3313 SWATCH-2475: Update docker-compose
  bin/wait-for
  docker-compose.yml
  init_dbs.sh
  postgresql.conf
Labels: QE Unneeded, Dev/approved

#3296 SWATCH-2278: Move denylist to swatch-contracts and provide functionality to load it
  poetry.lock
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/ProductDenylist.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/config/ProductDenylistTest.java
  swatch-contracts/src/test/resources/test-product-denylist.txt
  swatch-subscription-sync/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3300 SWATCH-2486: Include KAFKA_BILLABLE_USAGE_PARTITIONS in billable usage deployment
  swatch-billable-usage/deploy/clowdapp.yaml
Labels: Dev/approved, QE/approved

#3315 SWATCH-2482: Skip metered subscriptionUMB messages that do not have a billing provider
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/main/resources/liquibase/202404301614-terminate-duplicate-azure-subscriptions.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncLifecycleTest.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithSubscriptionSearchServiceWireMock.java
  swatch-contracts/src/main/resources/db/202405031420_terminate_azure_testing_subscriptions.xml
  swatch-contracts/src/main/resources/db/changeLog.xml
Labels: Dev/approved, QE/approved

#3287 SWATCH-1385 Drop UOM from billable usage messages
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
  src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceUnit.java
  src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
  src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsDimensionNotConfiguredException.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/ErrorCode.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageAggregateProcessor.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/exception/AzureDimensionNotConfiguredException.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/exception/ErrorCode.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
Labels: Dev/approved, QE/approved

#3172 SWATCH-1622 Resolve incoming Event conflicts and amend differences
  src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
  src/main/java/org/candlepin/subscriptions/event/EventConflictResolver.java
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/java/org/candlepin/subscriptions/event/ResolvedEventMapper.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
  src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/event/EventConflictResolverTest.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  src/test/java/org/candlepin/subscriptions/event/ResolvedEventMapperTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
  swatch-model-events/schemas/base_event.yaml
  swatch-model-events/schemas/clean_up_event.yaml
  swatch-model-events/schemas/event.yaml
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryServiceConfiguration.java
Labels: Dev/approved, QE/approved

#3299 SWATCH-2483: Fix export subscriptions service to filter by payg
  src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionCsvDataMapperService.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
  src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: Dev, QE/approved

#3309 SWATCH-2504: Replace the fact normalizer identification
  src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Labels: Dev/approved, QE/approved

#3335 SWATCH-2535: Reset account by org ID to use the billable usage client
  build.gradle
  clients/billable-usage-client/billable-usage-client-config.json
  clients/billable-usage-client/src/main/java/com/redhat/swatch/billable/usage/client/BillableUsageApiFactory.java
  clients/build.gradle
  clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
  settings.gradle
  src/main/java/org/candlepin/subscriptions/tally/AccountResetService.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageClientProperties.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  swatch-billable-usage/build.gradle
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceEntity.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
  swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3333 SWATCH-431: Update event data json to copy uom to metric_id
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/resources/liquibase/202405080950-copy-uom-to-metric-id-events-table.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Labels: Dev/approved, QE/approved

#3294 SWATCH-2333: Added attribute to subcription definition for isVdcType
  src/main/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollectorFactory.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
  src/test/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollectorFactoryTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_ARM.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_IBM_Power.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_IBM_z.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_SAP_x86.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_EUS.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_ha.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_rs.yaml
Labels: Dev/approved, QE/approved

#3347 SWATCH-2531 Populate unleash in EEs
  .unleash/Dockerfile.unleash
  bin/import-features.sh
  dependencies.gradle
  deploy/unleash-import-clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3237 SWATCH-2358: Only meter ELS 3rd party converted PAYG instances
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/main/java/org/candlepin/subscriptions/util/OfferingProductTagLookupService.java
  src/main/resources/liquibase/202404080930-add-special_pricing_flag-to-offering.xml
  src/main/resources/liquibase/changelog.xml
  src/main/resources/product-stub-data/tree-RH02781MO_attrs-true.json
  src/test/java/org/candlepin/subscriptions/db/model/EventRecordTest.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
  swatch-core/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/util/MeteringEventFactoryTest.java
  swatch-model-events/schemas/event.yaml
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Labels: Dev/approved, QE/approved

#3341 SWATCH-2361: rhsm-conduit should forward the conversions.activity to HBI
  clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
  swatch-system-conduit/schemas/inventory/hbi-system-profile-conversions.yaml
  swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
  swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Labels: Dev/approved, QE/approved

#3349 SWATCH-2520: Calculate capacity for all the metrics
  src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
Labels: Dev, QE/approved

#3292 SWATCH-2478: Add billable usage UUIDs to aggregates so we can update retry_on
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/processors/BillableUsageAggregateProcessorTest.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: Dev/approved, QE/approved

#3301 SWATCH-2494: Add all status of billable usage remittance together
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
Labels: Dev/approved, QE/approved

#3368 SWATCH-2578 Offering should get updated when special_pricing_flag is updated
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingEntity.java
  swatch-contracts/src/main/resources/db/202405222240_add_offering_special_product_tag_h2_only.xml
  swatch-contracts/src/main/resources/db/changeLog.xml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
Labels: Dev/approved, QE/approved

#3330 SWATCH-2145: Prevent tallies from creating duplicate system/host entries
  src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
  src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
  src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
  src/main/resources/liquibase/202405061230-remove-duplicated-hosts.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
  src/test/java/org/candlepin/subscriptions/inventory/db/InventoryRepositoryIT.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
  src/test/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollatorTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Labels: Dev/approved, QE/approved

#3360 SWATCH-2523: Updates contract entity to join Offering entity
  clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
  src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractDtoMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractOfferingMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncService.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/main/resources/db/202405210900_change_product_id_nullable.xml
  swatch-contracts/src/main/resources/db/changeLog.xml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/SubscriptionEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/ContractRepositoryTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Labels: Dev/approved, QE/approved

#3381 Refactor SubscriptionDefinition and Variant lookups and Move Product Tag detection out of FactNormalizer
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
  src/main/java/org/candlepin/subscriptions/tally/facts/ProductNormalizer.java
  src/main/java/org/candlepin/subscriptions/util/OfferingProductTagLookupService.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/ProductNormalizerTest.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Labels: QE Unneeded, Dev

#3354 SWATCH-2518: Create subscription capacity view for the export service
  src/main/java/org/candlepin/subscriptions/export/CsvExportFileWriter.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionCsvDataMapperService.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionJsonDataMapperService.java
  src/main/resources/liquibase/202405160950-add-subscription-capacity-view.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core/schemas/subscriptions_export_csv_item.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityViewMetric.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/converters/SubscriptionCapacityViewMetricConverter.java
Labels: Dev/approved, QE/approved
