Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-09, with the labels that each got.

#3700 SWATCH-2862: Purge tally measurements in batches
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
  src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Labels: QE Unneeded, Dev/approved

#3699 SWATCH-2855: Truncate start/end dates when syncing contracts from IT Partner gateway
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
Labels: Dev/approved

#3704 SWATCH-2870: Configure rest-client timeouts in swatch-contracts
  CONTRIBUTING.md
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3686 SWATCH-2853: Add additional SKUs to the deny list
  swatch-contracts/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3710 SWATCH-2871: Handle azure contracts measurements in MeasurementMetricIdTransformer
  swatch-contracts/build.gradle
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformerTest.java
Labels: QE Unneeded, Dev/approved

#3711 delete unused env vars
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3627 SWATCH-2696: sync metered offering subscriptions from IT partner gateway
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/PartnerEntitlementsRequest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractUMBMessageConsumer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncService.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AwsContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceSubscriptionTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncLifecycleTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Labels: Dev/approved, QE/approved

#3668 SWATCH-2505 Remove use of uom for Sku Capacity Report from v1
  api/rhsm-subscriptions-api-v1-spec.yaml
  src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionResourceV1.java
  src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableController.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionResourceV1Test.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
Labels: Dev/approved, QE/approved

#3701 SWATCH-2175: Meter ROSA Classic
  swatch-metrics/src/main/resources/application.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
  swatchdog/swatchdog/prometheus/command.py
Labels: Dev/approved, QE/approved

#3712 SWATCH-2755 Enable wiremock for internal swatch contract url
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/ContractsController.java
  swatch-billable-usage/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#3718 swatch-2690: event schema updates
  swatch-model-events/schemas/event.yaml
Labels: QE Unneeded, Dev

#3746 SWATCH-2907: Populate description in RetryWithExponentialBackoff
  swatch-billable-usage/src/main/resources/application.properties
  swatch-common-smallrye-fault-tolerance/src/main/java/com/redhat/swatch/faulttolerance/interceptors/RetryWithExponentialBackoffInterceptor.java
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3708 SWATCH-2813: Use specific clientId's credential in swatch-producer-azure
  clients/azure-marketplace-client/azure-marketplace-api-spec.yaml
  clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
  src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
  src/main/spec/internal-subscriptions-sync-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceClientFactory.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceService.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/model/AzureClient.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureMarketplaceServiceTest.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/WireMockResource.java
Labels: Dev/approved, QE/approved

#3725 SWATCH-2160: Increase SubscriptionDefinition lookup speed
  dependencies.gradle
  src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/ContractsControllerTest.java
  swatch-product-configuration/build.gradle
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistry.java
Labels: QE, Dev/approved

#3705 SWATCH-2830: Update docs with info on how API docs are generated
  docs/api-documentation.md
Labels: QE Unneeded, Dev/approved

#3748 SWATCH-2897 Internal api to provide remittance response based on tally_id
  swatch-billable-usage/build.gradle
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceFilter.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/model/RemittanceMapper.java
  swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
Labels: Dev/approved, QE/approved

#3729 SWATCH-2864: Prune included products when syncing offerings
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingProductTagLookupService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingProductTagLookupServiceTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: Dev/approved, QE/approved

#3740 SWATCH-2736: Resize resource requests on curl containers.
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-contracts/deploy/clowdapp.yaml
  swatch-metrics/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3760 Expose swagger ui for billable usage component
  swatch-billable-usage/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3753 SWATCH-2917: Improve logging to identify system being updated in conduit
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Labels: QE Unneeded, Dev/approved

#3756 SWATCH-2925: Handle NumberFormatException for cores/sockets
  swatch-contracts/src/main/java/com/redhat/swatch/contract/product/UpstreamProductData.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/product/UpstreamProductDataTest.java
Labels: QE, Dev/approved

#3770 SWATCH-2935: Improve find guests DB query
  swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
Labels: QE Unneeded, Dev/approved

#3766 SWATCH-2887: Delete host tally buckets after processing event batches
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
Labels: QE Unneeded, Dev/approved

#3738 SWATCH-2910: Filter snapshots by supported metric in the product
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
Labels: Dev/approved, QE/approved

#3778 SWATCH-2925 Avoid NPE and Array out of bound exception
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/PartnerEntitlementsRequest.java
Labels: Dev/approved

#3775 SWATCH-2925: Prevent swatch contract service restarts on failures
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#3793 SWATCH-2960: Increase timeout to get azure/aws context
  swatch-common-smallrye-fault-tolerance/src/main/java/com/redhat/swatch/faulttolerance/api/RetryWithExponentialBackoff.java
  swatch-common-smallrye-fault-tolerance/src/main/java/com/redhat/swatch/faulttolerance/interceptors/RetryWithExponentialBackoffInterceptor.java
  swatch-common-smallrye-fault-tolerance/src/test/java/com/redhat/swatch/faulttolerance/interceptors/RetryWithExponentialBackoffInterceptorTest.java
  swatch-producer-aws/build.gradle
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/build.gradle
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#3794 SWATCH-2943: Improve performance of query for subscriptions table v2
  src/main/resources/liquibase/202409251400-update-subscription-capacity-view-org-id.xml
  src/main/resources/liquibase/changelog.xml
Labels: QE Unneeded, Dev/approved

#3776 SWATCH-1233: Drop UOM from the swatch
  api/rhsm-subscriptions-api-v1-spec.yaml
  bin/BASILISK.csv
  bin/events.csv
  bin/import-events.py
  bin/insert-mock-hosts
  src/main/java/org/candlepin/subscriptions/event/EventConflictResolver.java
  src/main/java/org/candlepin/subscriptions/event/EventNormalizer.java
  src/main/java/org/candlepin/subscriptions/event/UsageConflictKey.java
  src/main/java/org/candlepin/subscriptions/event/UsageConflictTracker.java
  src/main/java/org/candlepin/subscriptions/resource/api/v1/InstancesResource.java
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
  src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
  src/main/spec/internal-tally-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/event/EventConflictResolverTest.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  src/test/java/org/candlepin/subscriptions/event/ResolvedEventMapperTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/InstancesResourceTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
  src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/MetricMapper.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
  swatch-core/src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
  swatch-metrics/schemas/metrics_task_descriptor.yaml
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/util/MeteringEventFactoryTest.java
  swatch-model-events/schemas/event.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Labels: Dev/approved, QE/approved

#3799 SWATCH-2960: Increase usage hourly consumer timeout and context retries
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE, Dev/approved

#3800 SWATCH-2970: Fix the contract API certificate configuration in azure svc
  swatch-billable-usage/src/main/resources/application.properties
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#3802 Remove logic to force sync an org during UsageContext lookup
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProvider.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProviderTest.java
Labels: QE Unneeded, Dev/approved
