Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-11, with the labels that each got.

#3892 SWATCH-2299: Use micrometer to count tally values by product, metric, and billing ID
  src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
  src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerMetricsTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: QE, Dev

#3904 Configure pre-commit hook to run spotlessCheck task
  .pre-commit-config.yaml
  docs/pre-commit.md
Labels: QE Unneeded, Dev/approved

#3902 Bump quarkusVersion from 3.15.1 to 3.16.1
  CONTRIBUTING.md
  buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
  dependencies.gradle
  swatch-billable-usage/build.gradle
  swatch-billable-usage/src/main/resources/application.properties
  swatch-common-kafka/build.gradle
  swatch-common-trace-response/build.gradle
  swatch-contracts/build.gradle
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ResourceRolesAllowedTest.java
  swatch-metrics-hbi/build.gradle
  swatch-metrics/build.gradle
  swatch-model-billable-usage/build.gradle
  swatch-producer-aws/build.gradle
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/build.gradle
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved

#3899 SWATCH-2969: Configure the logging to NOT use json format in Quarkus
  swatch-metrics/build.gradle
  swatch-metrics/src/main/resources/application.yaml
  swatch-producer-aws/build.gradle
  swatch-producer-aws/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#3761 SWATCH-2145: Merge duplicate hosts from different sources in tally
  src/main/java/org/candlepin/subscriptions/tally/admin/DataMigrationRunner.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
  src/main/java/org/candlepin/subscriptions/tally/admin/MergeHostsMigration.java
  src/main/spec/internal-tally-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/tally/admin/MergeHostsMigrationTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Labels: Dev/approved, QE/approved

#3915 SWATCH-2584: Ensure python scripts use the module requests > 2.32.0
  .gitignore
  bin/check_vulnerabilities.py
  bin/import-events.py
  poetry.lock
  pyproject.toml
Labels: QE Unneeded, Dev/approved

#3917 Fix event trigger for swatch-metrics-hbi-push pipeline.
  .tekton/swatch-metrics-hbi-push.yaml
Labels: QE Unneeded, Dev/approved

#3886 SWATCH-3049: Enable observation in Spring Boot services for Kafka
  .gitignore
  README.md
  config/otel/docker-compose.yml
  config/wiremock/__files/prometheus_success.json
  config/wiremock/docker-compose.yml
  config/wiremock/mappings/prometheus_query_success.json
  config/wiremock/mappings/prometheus_queryrange_success.json
  docs/playbooks/observability.md
  src/main/java/org/candlepin/subscriptions/capacity/CapacityIngressConfiguration.java
  src/main/java/org/candlepin/subscriptions/resource/ApiConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
  stub/mappings/README.md
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/TaskConsumerConfiguration.java
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaConfigurator.java
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskConsumerFactory.java
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProcessor.java
  swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java
  swatch-core/src/main/java/org/candlepin/subscriptions/tracing/TracingConfiguration.java
  swatch-core/src/main/java/org/candlepin/subscriptions/tracing/TracingService.java
  swatch-core/src/main/resources/logback-spring.xml
  swatch-core/src/main/resources/swatch-core/application.yaml
  swatch-metrics/src/main/resources/application.yaml
Labels: QE Unneeded, Dev/approved

#3923 SWATCH-3062: Use isPaygEligible when doing tally hourly in payg products
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: Dev/approved, QE/approved

#3928 SWATCH-3066: Log traces for "com.redhat.swatch" in spring services
  swatch-api/deploy/clowdapp.yaml
  swatch-metrics/deploy/clowdapp.yaml
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev

#3870 Container update to apply openssl security fix
  Dockerfile
  swatch-billable-usage/src/main/docker/Dockerfile.jvm
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
Labels: QE Unneeded, Dev/approved

#3924 SWATCH-2936: Prevent retries when handling export requests
  src/main/java/org/candlepin/subscriptions/export/ExportRequestConsumer.java
  swatch-common-export/src/main/java/com/redhat/swatch/export/ExportRequestHandler.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/ExportRequestConsumer.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/export/SubscriptionDataExporterServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ExportServiceWireMockResource.java
Labels: QE Unneeded, Dev/approved

#3930 SWATCH-3072: Better clowder truststore handling
  README.md
  buildSrc/src/main/groovy/swatch.java-conventions.gradle
  swatch-core/src/main/java/org/candlepin/subscriptions/actuator/CertInfoContributor.java
  swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJsonEnvironmentPostProcessor.java
  swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJsonPropertySource.java
  swatch-core/src/main/java/org/candlepin/subscriptions/clowder/KafkaSslBeanPostProcessor.java
  swatch-core/src/test/java/org/candlepin/subscriptions/clowder/ClowderJsonPropertySourceTest.java
Labels: QE Unneeded, Dev/approved

#3961 SWATCH-2297: Rename metric for ingested usage data from Prometheus
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
Labels: QE, Dev/approved

#3964 Configure Jenkins pipelines to use kubedock latest image
  Jenkinsfile
Labels: Dev/approved

#3955 SWATCH-3108: Use feeds name when openshift cluster uuid does not exist
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Labels: Dev/approved, QE/approved

#3933 SWATCH-2304: Add a metric for usage aggregated per hour
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
Labels: Dev/approved, QE/approved

#3970 Extract cross-cutting models that were duplicated in swatch-contracts into a smaller library
  build.gradle
  dependencies.gradle
  settings.gradle
  swatch-common-models/build.gradle
  swatch-common-models/src/main/java/com/redhat/swatch/common/model/HardwareMeasurementType.java
  swatch-common-models/src/main/java/com/redhat/swatch/common/model/ServiceLevel.java
  swatch-common-models/src/main/java/com/redhat/swatch/common/model/StringValueEnum.java
  swatch-common-models/src/main/java/com/redhat/swatch/common/model/Usage.java
  swatch-contracts/build.gradle
  swatch-contracts/src/main/java/com/redhat/swatch/contract/product/UpstreamProductData.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/DbReportCriteria.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/Granularity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityView.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ResourceUtils.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/ApiModelMapperV1.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/ApiModelMapperV2.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/SubscriptionCsvDataMapperService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/SubscriptionDataExporterService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/SubscriptionJsonDataMapperService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/product/UpstreamProductDataTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/SubscriptionRepositoryTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1Test.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1Test.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProviderTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/export/SubscriptionDataExporterServiceTest.java
Labels: QE Unneeded, Dev

#3968 SWATCH-3126: Improve traceability for swatch conduit service
  clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
  docs/playbooks/observability.md
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/tasks/UpdateOrgInventoryTask.java
Labels: QE Unneeded, Dev/approved

#3966 Allow response content to be json formatted
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics-hbi/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.yaml
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#3974 SWATCH-3109 Remove retry logic from swatch-billable-usage and billing producers
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/configuration/ApplicationConfiguration.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/configuration/Channels.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageDeadLetterConsumer.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
  swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/InMemoryMessageBrokerKafkaResource.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageDeadLetterConsumerTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: Dev/approved, QE/approved

#3953 SWATCH-2003: Enable wiremock testing in EE for azure
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/file/AzureMarketplaceProperties.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceClientFactory.java
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#3979 SWATCH-3133: Remove leftovers around the subscription service config
  build.gradle
  src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
  src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
  src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationConfiguration.java
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceSubscriptionCollector.java
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/PruneSubscriptionsTask.java
  src/main/java/org/candlepin/subscriptions/subscription/SearchApiFactory.java
  src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionConfiguration.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
  src/main/resources/application-capacity-ingress.yaml
  src/main/resources/application.yaml
  src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceSubscriptionCollectorTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionServiceTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
  swatch-core-test/src/main/resources/application-test.yaml
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3980 SWATCH-3050: Update usage context subscriptions counters by product
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProvider.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProviderTest.java
Labels: QE, Dev/approved

#3949 SWATCH-2303: Add a metric to swatch-producer-azure for metered usage
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
Labels: QE, Dev/approved

#3957 SWATCH-2302: Capture AWS message transmission statuses in micrometer
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
Labels: Dev/approved, QE/approved
