Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-06, with the labels that each got.

#3336 SWATCH-2492: Remove use of Azure Tenent Id in the billing account id
  src/main/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProvider.java
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/resources/liquibase/202405151547-update-events-azure-billable-account-id.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
  src/test/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProviderTest.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
  swatch-model-events/schemas/event.yaml
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: Dev/approved, QE/approved

#3380 SWATCH-2586: Change sourcePartner type to string
  clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractSourcePartnerEnum.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Labels: Dev/approved, QE/approved

#3391 Revert "SWATCH-2145: Prevent tallies from creating duplicate system/host entries (#3330)"
  src/main/resources/liquibase/202406030700-drop-unique-constraints-in-hosts.xml
  src/main/resources/liquibase/changelog.xml
Labels: QE Unneeded, Dev/approved

#3379 SWATCH-2588: Do not clear measurements for offerings with metered
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
  src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
  src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Labels: Dev, QE/approved

#3337 SWATCH-2522: Skip syncing subscriptionUMB messages for newly created contracts
  src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
  src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/main/resources/liquibase/202405081325-delete-duplicate-aws-subscriptions.xml
  src/main/resources/liquibase/changelog.xml
  src/main/spec/internal-subscriptions-sync-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AwsContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
Labels: Dev/approved, QE/approved

#3382 SWATCH-2576 Fix LazyInitializationException during subscription sync
  src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Labels: Dev/approved

#3395 SWATCH-2217: Add ocp cluster data floorplan
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#3393 SWATCH-2514: SAP variant showing incorrect usage graph
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_EUS.yaml
Labels: Dev/approved, QE/approved

#3397 Prevent unique constraints in the 202405151547-update-events-azure-billable-account-id.xml
  src/main/resources/liquibase/202405151547-update-events-azure-billable-account-id.xml
Labels: QE Unneeded, Dev

#3400 SWATCH-2583: Do not remove unseen finest granularity measurements
  src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
  src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java
Labels: Dev/approved, QE/approved

#3411 Update grafana dashboard to latest in stage
  .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
Labels: QE Unneeded, Dev/approved

#3402 Allow to set the API version to use separately by endpoint
  api/rhsm-subscriptions-api-spec.yaml
  build.gradle
  src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/InternalProducerRedHatMarketplaceApiResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/InternalProducerRedHatMarketplaceApiYamlResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/InternalSubscriptionSyncApiResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/InternalSubscriptionSyncApiYamlResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/InternalTallyApiJsonResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/InternalTallyApiResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/OpenApiJsonResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/OpenApiResource.java
  src/main/java/org/candlepin/subscriptions/resteasy/JaxrsApplication.java
  src/main/java/org/candlepin/subscriptions/rhmarketplace/api/admin/InternalRhMarkeplaceResource.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
  src/main/resources/application-rh-marketplace.yaml
  src/main/spec/internal-subscriptions-sync-api-spec.yaml
  src/main/spec/internal-swatch-producer-red-hat-marketplace-api-spec.yaml
  src/main/spec/internal-tally-api-spec.yaml
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ConsumerApiSpecEqualityTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3412 Update tally consumer group name to new swatch-billable-usage
  .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
Labels: QE Unneeded, Dev/approved

#3407 Normalize event measurements to metric_id on receipt
  docker-compose.yml
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
  swatch-model-events/schemas/event.yaml
Labels: Dev/approved, QE/approved

#3425 Work around HBI DB connection failure on startup
  docker-compose.yml
Labels: QE Unneeded, Dev/approved

#3392 swatch-2595: retry billable usage no billing account
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
  swatch-contracts/src/main/resources/db/202406111405_change_billing_account_id_nullable.xml
  swatch-contracts/src/main/resources/db/changeLog.xml
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/resources/application.properties
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: Dev/approved, QE/approved

#3377 SWATCH-2289: Add billable usage status consumer to update status on records
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/configuration/Channels.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/InMemoryMessageBrokerKafkaResource.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
Labels: QE, QE Unneeded, Dev/approved

#3396 Add strimzi kafka bridge to compose file
  config/application-kafka-bridge.properties
  docker-compose.yml
Labels: QE Unneeded, Dev/approved

#3362 SWATCH-2360, SWATCH-2401, SWATCH-2404 Support RHEL conversions records coming from HBI
  bin/insert-mock-hosts
  src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
  src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
  src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
  src/main/java/org/candlepin/subscriptions/tally/facts/ProductNormalizer.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/ProductNormalizerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Labels: QE, Dev/approved

#3428 SWATCH-2624: Don't log errors after missing permissions in exports
  src/main/java/org/candlepin/subscriptions/export/ExportSubscriptionListener.java
  src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithExportServiceWireMock.java
Labels: QE Unneeded, Dev/approved

#3434 SWATCH-2649 Add sku_product_tag index for performance
  src/main/resources/liquibase/202406130700-add-index-in-sku-product-tag.xml
  src/main/resources/liquibase/changelog.xml
Labels: QE Unneeded, Dev

#3433 SWATCH-2647: swatch-metrics no longer skips event creation for els-payg-addon
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: QE, Dev/approved

#3441 SWATCH-2658: Use billing_marketplace_instance_id as instance key for rhelemeter
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
Labels: Dev/approved, QE/approved

#3394 SWATCH-2579 Prevent subscription duplication on quantity change
  src/main/java/org/candlepin/subscriptions/liquibase/LiquibaseCustomTask.java
  src/main/java/org/candlepin/subscriptions/liquibase/PopulateSubscriptionMeasurements.java
  src/main/java/org/candlepin/subscriptions/liquibase/RemoveIncorrectlySegmentedSubscriptions.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/main/resources/liquibase/202406051539-remove-erroneously-duplicated-subscriptions.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
  swatch-billable-usage/build.gradle
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillingProvider.java
  swatch-producer-aws/build.gradle
  swatch-producer-azure/build.gradle
Labels: QE, Dev/approved

#3437 SWATCH-2521: Remove use of subscription_product_ids table
  src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
  src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
  src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
  src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
  src/test/java/org/candlepin/subscriptions/subscription/export/PerformanceSubscriptionDataExporterServiceIT.java
  src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionProductIdEntity.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/SubscriptionEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/DbReportCriteria.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Labels: QE Unneeded, Dev/approved

#3450 SWATCH-2670 Group RemittanceSummaryProjections by hardware measurement type
  src/main/java/org/candlepin/subscriptions/event/EventConflictResolver.java
  src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceFilter.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceSummaryProjection.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepositoryTest.java
Labels: Dev/approved, QE/approved

#3432 SWATCH-2644: Add filter for orgId ++ increase performance of view
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionCsvDataMapperService.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionJsonDataMapperService.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
  src/main/resources/liquibase/202406120950-update-subscription-capacity-view.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/ProductId.java
Labels: Dev/approved, QE/approved

#3459 SWATCH-2618 Add better logging for AWS Azure usage
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageAggregateProcessor.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
Labels: QE Unneeded, Dev/approved

#3447 Updates to closer align the swatch_producer_aws structure with swatch_producer_azure
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/configuration/ProfileFileConfiguration.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/file/AwsCredentialsLookup.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/resource/BillableUsageResource.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsMarketplaceMeteringClientFactory.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/BillableUsageProducer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/file/AwsCredentialsLookupTest.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsUsageContextLookupApiTest.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: QE Unneeded, Dev/approved

#3386 SWATCH-2572 Configure Ansible-aaS
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/main/resources/subscription_configs/Ansible/ansible-aap-managed.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Labels: Dev/approved, QE/approved

#3467 SWATCH-2684: Set azure billing info from existing subscription during sync
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
Labels: Dev/approved

#3460 SWATCH-2686: Add index for subscription-number to the subscription table
  src/main/resources/liquibase/202406240700-add-subscription-number-index.xml
  src/main/resources/liquibase/changelog.xml
Labels: Dev/approved
