Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-04, with the labels that each got.

#3202 SWATCH-2390: Disable separate Quarkus management port during testing
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.yaml
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3189 SWATCH-1957 Remove use of product name while emitting usage
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Labels: QE, Dev/approved

#3190 SWATCH-2346: Also check dmi.bios.vendor for aws host detection
  .unleash/flags.json
  docker-compose.yml
  init_dbs.sh
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Labels: Dev/approved, QE/approved

#3207 Fix tally_snapshot.yaml to remove duplicated metric_id property
  swatch-core/schemas/tally_snapshot.yaml
Labels: QE Unneeded

#3208 SWATCH-2285: Add swatch-billable-usage deployment
  pr_check.sh
  swatch-billable-usage/deploy/clowdapp.yaml
Labels: QE Unneeded

#3204 SWATCH-2317: Move use of UOM to MetricId in tally
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapper.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillingUnit.java
  src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapperTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/QuantityTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceFilter.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/kafka/BillableUsageAggregateKey.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/kafka/streams/BillableUsageAggregateKey.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
Labels: QE Unneeded, Dev/approved

#3213 SWATCH-2038: Bump Quarkus to 3.9.2 && Update the swatch-product-configuration module to be framework-agnostic
  dependencies.gradle
  swatch-product-configuration/build.gradle
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Defaults.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: QE Unneeded, Dev/approved

#3178 SWATCH-2277: Generate Subscription Sync API to swatch-contracts
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/CapacityResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/DefaultExceptionMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/SubscriptionSyncResource.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
Labels: Dev/approved, QE/approved

#3194 Add Spring hot deployment to Clowdapps without it
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
  swatchdog/README.md
Labels: Dev/approved

#3209 SWATCH-2285: Create billable-usage service
  .github/dependabot.yml
  README.md
  bin/build-images.sh
  pr_check.sh
  settings.gradle
  swatch-billable-usage/README.md
  swatch-billable-usage/build.gradle
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/docker/Dockerfile.jvm
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/BillableUsageAggregationKeySerde.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/BillableUsageAggregationStreamProperties.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
  swatch-model-billable-usage/build.gradle
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregate.java
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregateDeserializer.java
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregateKey.java
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageSerializer.java
  swatch-producer-aws/build.gradle
  swatch-producer-aws/deploy/clowdapp.yaml
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/kafka/BillableUsageAggregate.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageAggregateProcessor.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageProducer.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/resource/BillableUsageResource.java
  swatch-producer-aws/src/main/resources/META-INF/openapi.yaml
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/processors/AwsUsageContextLookupApiTest.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/processors/BillableUsageAggregateProcessorTest.java
  swatch-producer-azure/build.gradle
  swatch-producer-azure/deploy/clowdapp.yaml
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/kafka/streams/BillableUsageAggregateKey.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/resource/BillableUsageResource.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageProducer.java
  swatch-producer-azure/src/main/resources/application.properties
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: QE Unneeded, Dev/approved

#3210 SWATCH-2318: Use metricid instead of UOM from billable usage messages
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
  src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
Labels: QE, Dev/approved

#3230 Remove reference to account_config table in insert-mock-hosts
  bin/insert-mock-hosts
Labels: Dev/approved

#3226 SWATCH-2412: Use saveAndFlush when consuming tally snapshots
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumer.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumerIT.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
Labels: QE Unneeded, Dev/approved

#3229 SWATCH-2428 Update event retention policy to 6 months
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
  src/main/java/org/candlepin/subscriptions/tally/events/EventRecordsRetentionProperties.java
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
  swatch-tally/deploy/clowdapp.yaml
Labels: Dev/approved

#3221 SWATCH-2421 Fix event and tally_state data
  src/main/resources/liquibase/202404051233-fix-bad-tally-state-and-event-data.xml
  src/main/resources/liquibase/changelog.xml
Labels: Dev/approved

#3236 Update pull request template with IQE info
  .github/pull_request_template.md
Labels: QE Unneeded, Dev/approved

#3246 SWATCH-2444: Fix bug with multiple azure API credentials
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceClientFactory.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceService.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureMarketplaceServiceTest.java
Labels: Dev/approved

#3234 SWATCH-2275: Add the product-client module for Quarkus
  buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
  clients/build.gradle
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/JsonProductDataSource.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductApiFactory.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductClient.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductDataSource.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductService.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/StubProductApi.java
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-MW00330.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-MW01484.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-MW01485.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-MW02164HR.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-RH00604F5.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-RH00618F5.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-RH0180191.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-RH3413336.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SKU00790.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCEUSRH34.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCHPNRH34.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCMPV4.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCMW01484A.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCMW01484B.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCMW01485.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH00003.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH00604.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH00618.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH01.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH01V4.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH34.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRH34V4.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCRS.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/engprods-SVCSFS.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-MW00210M1_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-MW00210MO_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-MW00330_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-MW01484_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-MW01485_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-MW02164HR_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-RH00604F5_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-RH00618F5_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-RH0180191_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-RH0180192_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-RH3413336_attrs-true.json
  clients/quarkus/product-client/src/main/resources/product-stub-data/tree-SKU00790_attrs-true.json
  clients/quarkus/product-client/src/test/java/com/redhat/swatch/clients/product/ProductServiceTest.java
  settings.gradle
  swatch-contracts/build.gradle
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/product/ProductApiConfigurationUsingStubsTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ResourceRolesAllowedTest.java
Labels: QE Unneeded, Dev/approved

#3220 SWATCH-2336: Increased max header size to accomodate actual use
  swatch-api/deploy/clowdapp.yaml
  swatch-metrics/deploy/clowdapp.yaml
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: Dev/approved, QE/approved

#3235 SWATCH-2408: Return both cores and sockets by default in the instances API
  src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
  src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
Labels: Dev/approved, QE/approved

#3228 Swatch-2413: billable usage aggregation flush
  swatch-billable-usage/build.gradle
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/FlushTopicService.java
  swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/FlushTopicServiceTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/InMemoryMessageBrokerKafkaResource.java
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregate.java
Labels: Dev/approved, QE/approved

#3245 SWATCH-2287 Add properties to billable usage remittance DB records
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
  src/main/resources/liquibase/202404121601-add-new-columns-billable-usage-remittance.xml
  src/main/resources/liquibase/changelog.xml
  src/main/spec/internal-billing-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceErrorCode.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceStatus.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceSummaryProjection.java
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregate.java
Labels: Dev/approved, QE/approved

#3218 SWATCH-2018: Report filtered instance data to Export Service in JSON
  src/main/java/org/candlepin/subscriptions/capacity/CapacityIngressConfiguration.java
  src/main/java/org/candlepin/subscriptions/export/DataExporterService.java
  src/main/java/org/candlepin/subscriptions/export/ExportClientConfiguration.java
  src/main/java/org/candlepin/subscriptions/export/ExportServiceRequest.java
  src/main/java/org/candlepin/subscriptions/export/ExportSubscriptionConfiguration.java
  src/main/java/org/candlepin/subscriptions/export/ExportSubscriptionListener.java
  src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
  src/main/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionRequestFilters.java
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
  src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
  src/main/resources/application-capacity-ingress.yaml
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core/schemas/instances_export.yaml
  swatch-core/schemas/instances_export_guest.yaml
  swatch-core/schemas/instances_export_item.yaml
  swatch-core/schemas/instances_export_metric.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstancesDbReportCriteria.java
  swatch-tally/deploy/clowdapp.yaml
Labels: Dev, QE/approved

#3260 Add LICENSE to container as required by OpenShift Container Policy
  Dockerfile
  swatch-billable-usage/src/main/docker/Dockerfile.jvm
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
Labels: QE Unneeded, Dev/approved

#3267 change billable usage aggergate debug log to info when aggregate is sent
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
Labels: QE Unneeded, Dev/approved

#3270 SWATCH-2464 Allow Kafka to use the system truststore
  swatch-billable-usage/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.yaml
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java
Labels: QE Unneeded, Dev/approved

#3265 SWATCH-2460: Move the /remittance/purge endpoint to the billing API
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
  src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
  src/main/spec/internal-billing-api-spec.yaml
  src/main/spec/internal-tally-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalBillingResourceTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev

#3264 SWATCH-2453: Add the contracts-client module for Quarkus
  clients/build.gradle
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/ContractsApiFactory.java
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/ContractsClient.java
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
  settings.gradle
  swatch-billable-usage/build.gradle
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/contracts/ContractsApiConfigurationUsingStubsTest.java
Labels: QE Unneeded, Dev/approved

#3269 SWATCH-2461: Add new field "currentTotal" into the snapshot model
  src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapper.java
  src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySummaryMapperTest.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapperTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-core/schemas/tally_snapshot.yaml
Labels: QE Unneeded, Dev

#3266 SWATCH-2288: Capture billable usage uuids in billable usage hourly aggregates
  src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
  src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
  swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregate.java
Labels: QE Unneeded, Dev/approved

#3278 SWATCH-2364: Append azureCustomerId to the end of billingProviderId
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Labels: QE, Dev/approved

#3274 SWATCH-2328: Configure RestEasy Client to handle un-limited files
  src/main/java/org/candlepin/subscriptions/BootApplication.java
  src/test/java/org/candlepin/subscriptions/subscription/export/PerformanceSubscriptionDataExporterServiceIT.java
  src/test/java/org/candlepin/subscriptions/test/ExtendWithExportServiceWireMock.java
Labels: QE Unneeded, Dev/approved

#3276 SWATCH-1384: Drop UOM from tally summary messages
  src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
  src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
  src/test/java/org/candlepin/subscriptions/tally/TallySummaryMapperTest.java
  swatch-core/schemas/tally_snapshot.yaml
Labels: QE Unneeded, Dev/approved

#3295 SWATCH-2484 Offering without Metered Y flag are considered in PAYG
  src/main/java/org/candlepin/subscriptions/capacity/CapacityProductExtractor.java
  src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
  src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java
  src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
Labels: Dev/approved, QE/approved

#3251 Add .gitleaks.toml to reduce false positives on credential leak scans
  .gitleaks.toml
Labels: QE Unneeded, Dev/approved
