Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-07, with the labels that each got.

#3485 SWATCH-2673: Remove character limit from events instance_id column
  src/main/resources/liquibase/202406261514-alter-event-instance-id-length.xml
  src/main/resources/liquibase/changelog.xml
Labels: Dev, QE/approved

#3481 Disable dependabot container image updates
  .github/dependabot.yml
Labels: QE Unneeded, Dev/approved

#3458 SWATCH-2323: Add BillableUsage.tally_id to replace BillableUsage.id
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
  src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageMapper.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-producer-aws/.openapi-generator-ignore
  swatch-producer-aws/build.gradle
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsUsageContextLookupApiTest.java
  swatch-producer-azure/.openapi-generator-ignore
  swatch-producer-azure/build.gradle
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageDeadLetterTopicProducer.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Labels: Dev/approved, QE/approved

#3446 SWATCH-2514: Correction to product configuration placement
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_SAP_x86.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_EUS.yaml
Labels: Dev/approved, QE/approved

#3442 SWATCH-1358: Skip metering on metrics based on metered_by_rhel label
  swatch-metrics/src/main/resources/application.yaml
Labels: Dev/approved, QE/approved

#3496 SWATCH-2704 Cleanup Product Tag Determination
  src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
  src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
  src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
  src/main/java/org/candlepin/subscriptions/tally/facts/ProductNormalizer.java
  src/main/java/org/candlepin/subscriptions/util/OfferingProductTagLookupService.java
  src/test/java/org/candlepin/subscriptions/db/model/OfferingTest.java
  src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
  src/test/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollectorFactoryTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/ProductNormalizerTest.java
  src/test/resources/test_tag_profile.yaml
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageMapperTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/ContractsControllerTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/model/QuantityTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
  swatch-product-configuration/build.gradle
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/ProductTagLookupParams.java
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg_addon.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Labels: QE Unneeded, Dev

#3448 SWATCH-2020: Add CSV support to instances export
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperService.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
  src/main/resources/liquibase/202406191500-add-hypervisor_uuid-to-tally-instance-view.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core/schemas/instances_export_csv_item.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/MetricIdUtils.java
Labels: Dev, QE/approved

#3487 SWATCH-2424: Limit the snapshots to purge in batches
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicy.java
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicyProperties.java
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Labels: Dev/approved, QE/approved

#3454 SWATCH-2671 Set CloudProvider and hardware type on Event messages
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
Labels: Dev/approved, QE/approved, hold

#3520 Set the measurement type when creating buckets
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/resources/liquibase/202407091543-set-default-bucket-measurement-type.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Labels: Dev/approved, QE/approved

#3530 SWATCH-2738: Drop subscription_product_ids table that is no longer in use
  src/main/resources/liquibase/202407160722-drop-subscription-product-ids-table.xml
  src/main/resources/liquibase/changelog.xml
  swatch-tally/deploy/clowdapp.yaml
Labels: Dev/approved, QE/approved

#3503 SWATCH-2650 Implement level 1 and level 2 attr in offering
  src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
  src/main/java/org/candlepin/subscriptions/util/OfferingProductTagLookupService.java
  src/main/resources/liquibase/202407030751-add-level-column-for-offering-table.xml
  src/main/resources/liquibase/changelog.xml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingEntity.java
  swatch-contracts/src/main/resources/db/202407081616-add-level-columns-for-offering-table_h2_only.xml
  swatch-contracts/src/main/resources/db/changeLog.xml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
  swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/BadRequestExceptionMapper.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/ProductTagLookupParams.java
  swatch-product-configuration/src/main/resources/subscription_configs/Ansible/ansible-aap-managed.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Labels: Dev/approved, QE/approved

#3531 Update crc-bonfire and requests
  poetry.lock
Labels: QE Unneeded, Dev/approved

#3532 SWATCH-2740: Delete old subscription_measurement records when the contract metrics are updated
  swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionEntityMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionMeasurementEntity.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionMeasurementRepository.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceSubscriptionTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Labels: Dev/approved, QE/approved

#3538 SWATCH-2747: Adding no-remove-resource for deployed export-service
  pr_check.sh
Labels: Dev/approved

#3547 SWATCH-2752: Revert "SWATCH-2671 Set CloudProvider and hardware type on Event messages (#3454)
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
Labels: Dev/approved

#3534 SWATCH-2739: Add liquibase script for RHEL non payg measurement cleanup
  src/main/resources/liquibase/202407161214-clean-up-non-payg-measurements-on-rhel-systems.xml
  src/main/resources/liquibase/changelog.xml
Labels: Dev/approved, QE/approved

#3537 SWATCH-2744: Fix capacity reconciliation when another task is queued
  swatch-contracts/build.gradle
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/CapacityReconciliationService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/CapacityReconciliationIntegrationTest.java
Labels: Dev/approved, QE/approved

#3525 SWATCH-2733: Remove unused capacity API from contracts service
  clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/CapacityApiFactory.java
  src/main/java/org/candlepin/subscriptions/resource/ApiConfiguration.java
  src/main/java/org/candlepin/subscriptions/resource/api/v1/TallyResource.java
  src/main/resources/application-api.yaml
  src/test/java/org/candlepin/subscriptions/resource/api/v1/TallyResourceTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/CapacityResource.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ConsumerApiSpecEqualityTest.java
Labels: QE Unneeded, Dev

#3553 SWATCH-2744: Optimize the capacity reconciliation query via indexing
  src/main/resources/liquibase/202407231110-subscription-capacity-index.xml
  src/main/resources/liquibase/changelog.xml
Labels: QE Unneeded, Dev/approved

#3546 SWATCH-2705: Set ApplicationName on postgresql connection
  src/main/resources/application-worker.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-core/src/main/resources/swatch-core/application.yaml
Labels: QE Unneeded, Dev/approved

#3556 SWATCH-2746: Adjust log message that was logging an object with no toString
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Labels: QE Unneeded, Dev/approved

#3550 SWATCH-2726: Prevent send usages to other azure tenants if not forbidden
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/build.gradle
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/configuration/Channels.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceService.java
  swatch-producer-azure/src/main/resources/application.properties
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureMarketplaceServiceTest.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/InMemoryMessageBrokerKafkaResource.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/InjectWireMock.java
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/WireMockResource.java
Labels: Dev/approved, QE/approved

#3560 SWATCH-2676: Return status code 404 for non-existing sku when syncing
  src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
  src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
  src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
Labels: Dev/approved, QE/approved

#3573 SWATCH-2701 Reduce number of tally snapshot queries load to db
  src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
  src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
Labels: QE Unneeded, Dev/approved

#3561 SWATCH-2600: Prometheus mock data for EEs and local testing
  bin/metering-promql.py
  bin/prometheus-mock-data.sh
  poetry.lock
  pyproject.toml
  swatch-metrics/deploy/mock-prometheus-clowdapp.yaml
  swatchdog/swatchdog/__init__.py
  swatchdog/swatchdog/cli.py
  swatchdog/swatchdog/deploy/command.py
  swatchdog/swatchdog/prometheus/__init__.py
  swatchdog/swatchdog/prometheus/command.py
  swatchdog/swatchdog/prometheus/data_writer.py
Labels: QE, Dev/approved

#3580 SWATCH-2772: Set the OTEL protocol to grpc explicitly.
  swatch-api/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics/deploy/clowdapp.yaml
  swatch-metrics/src/main/resources/application.yaml
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved
