Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-12, with the labels that each got.

#3992 Fix grafana dashboard after subscriptions and contracts porting
  .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
  CONTRIBUTING.md
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#3932 Use Caddy to create iqe test proxy for ephemeral instances
  bin/caddy.yaml
  bin/iqe-ee-proxy.sh
Labels: Dev/approved, QE/approved

#4029 Force the compileJava order when building the projects in parallel
  buildSrc/src/main/groovy/swatch.quarkus-conventions.gradle
Labels: QE Unneeded, Dev, Dev/approved

#4027 SWATCH-3185: Fix duplicated traces in splunk for spring boot services
  docs/playbooks/observability.md
  swatch-core/src/main/resources/logback-spring.xml
Labels: QE Unneeded, Dev

#3906 SWATCH-2300: Add a metric for usage covered by a contract
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/model/Quantity.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
Labels: Dev/approved, QE/approved

#4004 SWATCH-3015: Add the kafka key with "org_id" to host-inventory topic
  swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryService.java
  swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java
Labels: Dev/approved, QE/approved

#4005 SWATCH-3128: Disabling Kafka client config providers
  Dockerfile
  swatch-api/deploy/clowdapp.yaml
  swatch-billable-usage/src/main/docker/Dockerfile.jvm
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-system-conduit/Dockerfile
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev

#4036 SWATCH-3134: Adding JVM config to disable the trimming of stack traces
  Dockerfile
  swatch-billable-usage/src/main/docker/Dockerfile.jvm
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
  swatch-system-conduit/Dockerfile
Labels: Dev/approved

#4034 Fix gradle bootRun command
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceWorkerConfiguration.java
  src/main/java/org/candlepin/subscriptions/tally/contracts/ContractsConfiguration.java
Labels: Dev/approved

#4031 SWATCH-3186: Fix null pointer exception when tallying snapshots
  src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
  src/test/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollatorTest.java
Labels: Dev/approved, QE/approved

#4030 SWATCH-3167: Add primary keys to all tables
  init_dbs.sh
  postgresql.conf
  src/main/resources/liquibase/202412041537-primary-keys-on-all-tables.xml
  src/main/resources/liquibase/changelog.xml
  swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
  swatch-contracts/src/main/resources/db/202412051144-primary-keys-on-changelog-table.xml
  swatch-contracts/src/main/resources/db/changeLog.xml
Labels: QE Unneeded, Dev/approved

#4057 Fix swatchdog
  swatchdog/swatchdog/deploy/command.py
Labels: QE Unneeded, Dev/approved

#4061 SWATCH-2941: Improve the export service logging to better troubleshoot
  swatch-common-export/build.gradle
  swatch-common-export/src/main/java/com/redhat/swatch/export/ExportRequestHandler.java
  swatch-common-export/src/main/java/com/redhat/swatch/export/utils/FileUtils.java
  swatch-common-export/src/test/java/com/redhat/swatch/export/utils/FileUtilsTest.java
Labels: QE Unneeded, Dev
