Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2024-08, with the labels that each got.

#3566 SWATCH-2730: Map instance guests in in CSV format
  src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperService.java
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core/schemas/instances_export_csv_item.yaml
Labels: Dev/approved, QE/approved

#3583 SWATCH-2674: Remove BillableUsage.id
  src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
  swatch-core/schemas/billable_usage.yaml
Labels: QE Unneeded, Dev/approved

#3590 RHCLOUD-34383: refactor: update build_deploy.sh
  build_deploy.sh
Labels: QE Unneeded, Dev/approved

#3570 Add kafka-bridge to EE deployment
  deploy_ephemeral_env.sh
  deploy_kafka_bridge.sh
  kafka-bridge.yaml
Labels: QE Unneeded, Dev/approved

#3585 SWATCH-2760 Finalize swatch-product-configuration for ansible-aap-managed
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  swatch-product-configuration/src/main/resources/subscription_configs/Ansible/ansible-aap-managed.yaml
Labels: QE, Dev/approved

#3597 SWATCH-2790: Use persist instead of saveOrUpdate in existing subs
  swatch-common-panache/src/main/java/com/redhat/swatch/panache/PanacheSpecificationSupport.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Labels: QE Unneeded, Dev

#3603 SWATCH-2742: key constraint exception during account reset
  bin/insert-mock-hosts
  src/main/java/org/candlepin/subscriptions/tally/AccountResetService.java
  src/test/java/org/candlepin/subscriptions/tally/AccountResetServiceTest.java
Labels: QE Unneeded, Dev/approved

#3607 Update pr_check.sh to increase iqe timeout
  pr_check.sh
Labels: Dev

#3599 SWATCH-2766: Fix 500 errors due to out-of-bounds page params
  src/main/java/org/candlepin/subscriptions/resource/api/v1/CapacityResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableController.java
  src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
  src/main/java/org/candlepin/subscriptions/util/InMemoryPager.java
Labels: Dev/approved, QE/approved

#3617 Add Spring Boot to Quarkus migration tips section
  CONTRIBUTING.md
Labels: QE Unneeded, Dev

#3621 SWATCH-2805: Log errors and ack offering sync messages when the offering sync fails
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncService.java
  swatch-contracts/src/main/resources/application.properties
Labels: Dev/approved

#3598 Fix NPE in BadRequestExceptionMapper
  src/main/java/org/candlepin/subscriptions/resource/api/v1/CapacityResource.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/CapacityResourceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/BadRequestExceptionMapper.java
Labels: Dev/approved, QE/approved

#3606 SWATCH-2766: Error reading denylist
  src/main/java/org/candlepin/subscriptions/capacity/files/ProductDenylist.java
  src/test/java/org/candlepin/subscriptions/files/ProductDenylistTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/ProductDenylist.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/utils/SubscriptionDtoUtil.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/config/ProductDenylistTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Labels: Dev/approved, QE/approved

#3612 SWATCH-2807 Fix filtering of prometheus events
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  swatch-metrics/README.md
  swatch-metrics/src/main/resources/application.yaml
Labels: Dev/approved, QE/approved

#3637 SWATCH-2816: Configure the PRODUCT_URL for prod in swatch contracts
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#3628 SWATCH-2675: Fix the property name for spring boot request limit
  build.gradle
  src/main/resources/application.yaml
  src/test/java/org/candlepin/subscriptions/deployment/ApiDeploymentTest.java
  swatch-api/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: Dev/approved, QE/approved

#3638 [HOTFIX] SWATCH-2816: Configure the PRODUCT_URL for prod in swatch contracts
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/resources/application.properties
Labels: Dev/approved

#3578 Use wiremock for ephemeral environment IT partner gateway api
  swatch-contracts/src/main/resources/application.properties
Labels: QE, Dev/approved

#3642 Correct errors with keystore references in swatch-contracts
  swatch-contracts/deploy/clowdapp.yaml
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
Labels: QE Unneeded, Dev/approved

#3645 Move repositories to settings.gradle
  dependencies.gradle
  settings.gradle
Labels: QE Unneeded, Dev/approved

#3626 SWATCH-2424: Delete inner query to purge the tally snapshots
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicy.java
  src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicyProperties.java
  src/main/resources/application-worker.yaml
  src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Labels: QE Unneeded, Dev/approved

#3654 Bump quarkusVersion from 3.9.2 to 3.12.3
  dependencies.gradle
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/CapacityReconciliationServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/EnabledOrgsProducerTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
Labels: QE Unneeded, Dev/approved

#3641 Quality of Line Improvements: validation and openApiGeneration
  build.gradle
  src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
  src/main/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProvider.java
  src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
  src/main/spec/internal-subscriptions-sync-api-spec.yaml
  src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
Labels: QE Unneeded, Dev/approved

#3657 Fix flaky test involving timestamp format
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsUsageContextLookupApiTest.java
Labels: QE Unneeded, Dev/approved

#3655 SWATCH-2826: Fix PAYG fingerprinting bug with role value
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Labels: Dev/approved, QE/approved

#3659 Konflux: Fix image specification for deprecated-base-image-check task
  .tekton/rhsm-push.yaml
  .tekton/swatch-api-push.yaml
  .tekton/swatch-contracts-push.yaml
  .tekton/swatch-metrics-push.yaml
  .tekton/swatch-producer-aws-push.yaml
  .tekton/swatch-producer-azure-push.yaml
  .tekton/swatch-producer-red-hat-marketplace-push.yaml
  .tekton/swatch-subscription-sync-push.yaml
  .tekton/swatch-system-conduit-push.yaml
  .tekton/swatch-tally-push.yaml
Labels: Dev

#3660 SWATCH-2809: Add traceresponse header to quarkus HTTP responses
  settings.gradle
  swatch-billable-usage/build.gradle
  swatch-common-trace-response/build.gradle
  swatch-common-trace-response/src/main/java/com/redhat/swatch/traceresponse/TraceResponseFilter.java
  swatch-contracts/build.gradle
  swatch-metrics/build.gradle
  swatch-producer-aws/build.gradle
  swatch-producer-azure/build.gradle
Labels: QE Unneeded, Dev/approved

#3665 SWATCH-2756: Product configuration for rhel-aus-addon
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_aus_addon.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_arm.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_ibm_power.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_ibm_z.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_sap_x86.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86_els.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86_els_payg.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86_els_payg_addon.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86_eus.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86_ha.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_x86_rs.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/satellite_capsule.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/satellite_server.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
Labels: Dev/approved, QE/approved

#3635 SWATCH-2771: Properly setup CORS on all services
  swatch-billable-usage/build.gradle
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RbacRolesAugmentor.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RbacRolesAugmentorTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/security/AntiCsrfFilter.java
  swatch-core/src/test/java/org/candlepin/subscriptions/security/AntiCsrfFilterTest.java
  swatch-metrics/src/main/resources/application.yaml
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/admin/api/MetricsTest.java
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/BillableUsageResourceIT.java
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#3675 SWATCH-2823: Update SAP product config to remove EUS
  swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_sap_x86.yaml
Labels: Dev/approved, QE/approved

#3579 SWATCH-2676: Update to error handling on SKU sync
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/DefaultExceptionMapper.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
Labels: Dev/approved, QE/approved

#3687 SWATCH-2804: Delete getSubscriptionById from SearchApi
  clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/StubSearchApi.java
  clients/subscription-client/subscription-api-spec.yaml
  src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Labels: QE Unneeded, Dev/approved

#3693 SWATCH-2827: Bump quarkusVersion from 3.12.3 to 3.14.1
  dependencies.gradle
  swatch-common-panache/src/main/java/com/redhat/swatch/panache/PanacheSpecificationSupport.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
Labels: QE Unneeded, Dev/approved
