Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-06, with the labels that each got.

#4537 SWATCH-3529: Migrate Quarkus Resteasy Reactive to Quarkus Resteasy extensions
  CONTRIBUTING.md
  buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
  swatch-billable-usage/build.gradle
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/build.gradle
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/DefaultExceptionMapper.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionResourceV1.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionResourceV2.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/ExportPskHeaderProvider.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1Test.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resteasy/PageLinkCreatorTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ExportServiceWireMockResource.java
  swatch-metrics/build.gradle
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/admin/api/InternalMeteringResource.java
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/admin/api/MetricsTest.java
  swatch-producer-aws/build.gradle
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/build.gradle
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceClientFactory.java
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#4583 Update README with swatch-database bonfire config
  README.md
Labels: QE Unneeded

#4589 Move DebugClientLogger into swatch-common-resteasy-client
  swatch-common-resteasy-client/src/main/java/com/redhat/swatch/resteasy/client/DebugClientLogger.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/config/DebugClientLoggerTest.java
  swatch-metrics/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4586 SWATCH-2844: Update nginx routing send capacity queries directly to s…
  swatch-api/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#4631 SWATCH-3663: Disable splunk DEV services to avoid random failures at start up
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics-hbi/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.properties
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4642 Change generated folder for the openapi plugins
  clients/pom.xml
  swatch-billable-usage/pom.xml
  swatch-contracts/pom.xml
  swatch-metrics/pom.xml
  swatch-model-billable-usage/pom.xml
  swatch-producer-aws/pom.xml
  swatch-producer-azure/pom.xml
Labels: Dev/approved

#4622 SWATCH-3640: Use the prometheus console-dot image
  bin/iqe-ee-proxy.sh
  swatch-metrics/deploy/mock-prometheus-clowdapp.yaml
Labels: QE Unneeded, Dev

#4697 SWATCH Metrics HBI: change the json deserialization strategy to not fail on unknown types
  swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiEvent.java
  swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiHostUnknownEvent.java
  swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/HbiEventDeserializationTest.java
  swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/services/HbiEventConsumerTest.java
  swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/test/helpers/HbiEventTestData.java
  swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/test/helpers/HbiEventTestHelper.java
  swatch-metrics-hbi/src/test/resources/data/hbi_physical_rhel_host_updated_event.json
  swatch-metrics-hbi/src/test/resources/data/hbi_unknown_event.json
Labels: QE Unneeded, Dev/approved

#4657 SWATCH-3664: Support instances to be mapped to different products/servide types
  src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
  src/main/java/org/candlepin/subscriptions/tally/admin/MergeHostsMigration.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
  swatch-database-migrations/src/main/resources/liquibase/202506191100-add-host-service-type-table.xml
  swatch-database-migrations/src/main/resources/liquibase/changelog.xml
Labels: Dev/approved, QE/approved

#4700 SWATCH-3345: Mark X509 authed users with service role
  swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RolesAugmentor.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RolesAugmentorTest.java
Labels: Dev
