Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-03, with the labels that each got.

#4218 SWATCH-3338: Add billing_account_id to SkuCapacity in subscriptions api v2
  api/rhsm-subscriptions-api-v2-spec.yaml
  src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
  src/test/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableControllerTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
Labels: Dev, QE/approved

#4239 SWATCH-3358: Use the metric "swatch_billable_usage_total" in the grafana dashboard to resolve all the variables
  .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Labels: QE Unneeded, Dev/approved

#4244 Hardcode the quarkus application name in quarkus.swagger-ui.path property
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#4238 SWATCH-3348: When offering sync, allow attributes with values 'N'
  swatch-contracts/src/main/java/com/redhat/swatch/contract/product/UpstreamProductData.java
  swatch-contracts/src/main/resources/product-stub-data/engprods-RH02781MO.json
  swatch-contracts/src/main/resources/product-stub-data/engprods-SVCRH02781.json
  swatch-contracts/src/main/resources/product-stub-data/tree-RH02781MO_attrs-true.json
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
Labels: Dev/approved, QE/approved

#4250 SWATCH-3373: Fix flaky test verifyCorrectUpdatesWhenRetryOccurs
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
Labels: QE Unneeded, Dev

#4215 swatch-3028 billing account id subscription api
  api/rhsm-subscriptions-api-v1-spec.yaml
  swatch-api/deploy/clowdapp.yaml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/BillingAccountInfoDTO.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionRepository.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/ContractsV1Resource.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RhIdentityPrincipal.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RolesAugmentor.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/SubscriptionRepositoryTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/ContractsV1ResourceTest.java
Labels: Dev/approved, QE/approved

#4254 SWATCH-3372: Update podman compose and test containers to use Postgresql 13
  .github/workflows/pr.yaml
  deploy/dev-clowdenv.yaml
  docker-compose.yml
  swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
Labels: Dev

#4258 SWATCH-3370: Host tally buckets sync is not updating the measurement type
  src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Labels: Dev/approved, QE/approved

#4283 SWATCH-3364: Improve troubleshooting when hosts didn't match any products
  src/main/java/org/candlepin/subscriptions/tally/facts/ProductNormalizer.java
  src/main/java/org/candlepin/subscriptions/tally/facts/product/ProductRule.java
  src/main/java/org/candlepin/subscriptions/tally/facts/product/QpcProductRule.java
  src/main/java/org/candlepin/subscriptions/tally/facts/product/RhsmProductsProductRule.java
  src/main/java/org/candlepin/subscriptions/tally/facts/product/SatelliteRoleProductRule.java
  src/main/java/org/candlepin/subscriptions/tally/facts/product/SystemProfileProductIdsProductRule.java
  src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/ProductNormalizerTest.java
  src/test/java/org/candlepin/subscriptions/tally/facts/product/QpcProductRuleTest.java
Labels: QE Unneeded, Dev/approved

#4247 SWATCH-3331 Change EE azure producer credential to a placeholder secret
  swatch-producer-azure/deploy/clowdapp.yaml
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved

#4277 SWATCH-3341: Update konflux pipelines to run junit tests
  .tekton/rhsm-pull-request.yaml
  .tekton/run-tests-task.yaml
  .tekton/swatch-api-pull-request.yaml
  .tekton/swatch-contracts-pull-request.yaml
  .tekton/swatch-metrics-hbi-pull-request.yaml
  .tekton/swatch-metrics-pull-request.yaml
  .tekton/swatch-producer-aws-pull-request.yaml
  .tekton/swatch-producer-azure-pull-request.yaml
  .tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
  .tekton/swatch-subscription-sync-pull-request.yaml
  .tekton/swatch-system-conduit-pull-request.yaml
  .tekton/swatch-tally-pull-request.yaml
Labels: QE Unneeded, Dev/approved

#4292 SWATCH-2844: Update nginx routing send capacity queries directly to swatch-contracts
  swatch-api/deploy/clowdapp.yaml
Labels: QE, Dev/approved
