Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-04, with the labels that each got.

#4317 SWATCH-3194 Add a panel in grafana to track rate limiting in swatch-producer-aws
  .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Labels: QE Unneeded, Dev/approved

#4336 Updating swatch-metrics-hbi clowdapp configuration
  swatch-metrics-hbi/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#4340 SWATCH-3461: Increase Billable Usage Memory Limit
  swatch-billable-usage/deploy/clowdapp.yaml
Labels: Dev/approved

#4324 SWATCH-3405: Add billing_account_id as param for Capacity
  api/rhsm-subscriptions-api-v1-spec.yaml
  src/main/java/org/candlepin/subscriptions/resource/api/v1/CapacityResource.java
  src/main/java/org/candlepin/subscriptions/resource/api/v1/TallyResource.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/CapacityResourceTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/TallyResourceTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1.java
  swatch-contracts/src/main/resources/META-INF/openapi.yaml
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1Test.java
Labels: Dev/approved, QE/approved

#4349 SWATCH-3476: Replace Counter.builder by registry.counter
  src/main/java/org/candlepin/subscriptions/event/EventController.java
  src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerMetricsTest.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
  swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
Labels: QE Unneeded, Dev/approved

#4352 SWATCH-3329: Add billing account info to subscription export
  swatch-contracts/schemas/subscriptions_export_csv_item.yaml
  swatch-contracts/schemas/subscriptions_export_json_item.yaml
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/SubscriptionCsvDataMapperService.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/SubscriptionJsonDataMapperService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/export/SubscriptionDataExporterServiceTest.java
Labels: QE, Dev/approved

#4364 Update ConfigMap name because of naming conflict
  .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Labels: QE Unneeded

#4365 Add required param to konflux pipeline
  .tekton/swatch-contracts-pull-request.yaml
  .tekton/swatch-metrics-hbi-pull-request.yaml
  .tekton/swatch-metrics-hbi-push.yaml
Labels: Dev/approved

#4393 Fix NPE in swatch-metrics-hbi when normalizing measurements for incoming events
  swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiHostCreateUpdateEvent.java
  swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiHostDeleteEvent.java
  swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/normalization/MeasurementNormalizer.java
  swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/services/HbiEventConsumer.java
  swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/normalization/MeasurementNormalizerTest.java
Labels: QE Unneeded, Dev/approved

#4396 Increase swatch-metrics-hbi resource allocations
  swatch-metrics-hbi/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#4390 Add tekton pipeline for swatch-billable-usage component
  .tekton/swatch-billable-usage-pull-request.yaml
  .tekton/swatch-billable-usage-push.yaml
Labels: QE Unneeded, Dev/approved

#4408 SWATCH-3530: Use branch to resolve product configuration
  pr_check.sh
Labels: QE, Dev/approved
