Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-07, with the labels that each got.

#4637 SWATCH-3180: Add level1/level2 identifiers for product tags using productName
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingProductTagLookupService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingProductTagLookupServiceTest.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/ProductTagLookupParams.java
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-dedicated-metrics.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-metrics.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/basilisk.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhacs.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhods.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Labels: Dev/approved, QE/approved

#4732 SWATCH-3623: Enable wiremock profile for azure producer for local component testing
  config/wiremock/__files/contract_service_response.json
  nginx.conf
  swatch-producer-azure/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#4714 Improve caching during container builds
  Dockerfile
  pom.xml
  swatch-billable-usage/src/main/docker/Dockerfile.jvm
  swatch-contracts/src/main/docker/Dockerfile.jvm
  swatch-database/src/main/docker/Dockerfile.jvm
  swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
  swatch-metrics/src/main/docker/Dockerfile.jvm
  swatch-producer-aws/src/main/docker/Dockerfile.jvm
  swatch-producer-azure/src/main/docker/Dockerfile.jvm
  swatch-system-conduit/Dockerfile
Labels: Dev/approved

#4745 Update the unleash fetch-toggles-interval in swatch-metrics-hbi
  swatch-metrics-hbi/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4757 SWATCH-3758: Allow to build the sources and run migrations using Makefile
  Makefile
Labels: QE Unneeded, Dev

#4759 SWATCH-3628: Enable wiremock profile for swatch-metrics for local component testing
  .gitignore
  config/prometheus/docker-compose.yml
  docker-compose.yml
  swatch-metrics/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4777 SWATCH-3754: Update default ports on Quarkus and Spring services
  src/main/resources/application-wiremock.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics-hbi/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.properties
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved

#4781 SWATCH-3753: Rename profile for local IQE testing to "dev"
  Makefile
  src/main/resources/application-dev.yaml
  swatch-billable-usage/src/main/resources/application.properties
  swatch-contracts/src/main/resources/application.properties
  swatch-metrics/src/main/resources/application.properties
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-azure/src/main/resources/application.properties
  swatch-system-conduit/src/main/resources/application-dev.yaml
Labels: Dev/approved

#4792 SWATCH-3691: Fix mapping rules in nginx for local testing
  nginx.conf
Labels: QE, Dev

#4794 SWATCH-3597: Restrict billing providers for /internal/rpc/tally/event…
  src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
  src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
Labels: Dev/approved, QE/approved

#4791 SWATCH-3759: Add a GitHub action to validate that all the services work in DEV mode
  .github/workflows/ci.yml
  bin/test-all-services.sh
  bin/test-service-health.sh
  docker-compose.yml
  swatch-billable-usage/src/main/resources/application.properties
Labels: QE Unneeded, Dev

#4801 Add pre-commit hooks for automated code formatting and style validation
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: QE Unneeded, Dev
