Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-05, with the labels that each got.

#4397 SWATCH-3391: Add RHACM product configuration
  swatch-metrics/src/main/resources/application.yaml
  swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhacm.yaml
  swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Labels: QE, Dev

#4463 SWATCH-3391: Fix logic to not assume `role` is always the same as the `product` label
  swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
Labels: QE, Dev

#4471 SWATCH-3542: Filter out billing_provider and billing_account_id with values _ANY from the instances/billing_account_ids API
  src/test/java/org/candlepin/subscriptions/db/AccountServiceInventoryRepositoryTest.java
  src/test/java/org/candlepin/subscriptions/resource/api/v1/InstancesResourceTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/HostTallyBucketRepository.java
Labels: QE, Dev/approved

#4481 SWATCH-3526: Remove REST Client stubs for Quarkus clients
  README.md
  clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/ContractsApiFactory.java
  clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/ContractsApiFactory.java
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/ContractsClient.java
  clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductApiFactory.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductClient.java
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductService.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApi.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiFactory.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiImpl.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacClient.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacService.java
  clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/StubRbacApi.java
  clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/SearchApiFactory.java
  clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/SearchClient.java
  clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/StubSearchApi.java
  src/main/resources/application-api.yaml
  src/main/resources/application-worker.yaml
  src/main/resources/application.yaml
  src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/ContractsController.java
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/contracts/ContractsApiConfigurationUsingStubsTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/RbacConfiguration.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionService.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/product/ProductApiConfigurationUsingStubsTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/product/UpstreamProductDataTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/rbac/RbacApiConfigurationUsingStubsTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ResourceRolesAllowedTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ProductStubForEngProductsWiremockExtension.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ProductStubForTreeWiremockExtension.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ProductUseStubService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/RbacUseStubService.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
  swatch-core-test/src/main/resources/application-test-inventory.yaml
  swatch-core-test/src/main/resources/application-test.yaml
  swatch-producer-red-hat-marketplace/README.adoc
  swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#4496 Remove DebugClientLogger from %stage to Reduce Log Noise
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4494 SWATCH-3456: Allow to mock product api responses for offering sync
  swatch-contracts/src/main/resources/application.properties
Labels: Dev/approved

#4510 SWATCH-3578: Adjust memory limit to memory limit ratio
  swatch-billable-usage/deploy/clowdapp.yaml
  swatch-contracts/deploy/clowdapp.yaml
  swatch-metrics/deploy/clowdapp.yaml
  swatch-subscription-sync/deploy/clowdapp.yaml
  swatch-system-conduit/deploy/clowdapp.yaml
  swatch-tally/deploy/clowdapp.yaml
Labels: QE Unneeded, Dev/approved

#4500 SWATCH-2579: Filter Capacity API by the most recent active subscription
  src/main/resources/liquibase/202505131100-update-subscription-capacity-view-to-filter-start-date.xml
  src/main/resources/liquibase/changelog.xml
  src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/SubscriptionRepositoryTest.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
Labels: Dev/approved, QE/approved

#4520 SWATCH-3527: Convert DebugClientLogger to use standard the JAX-RS API
  swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java
  swatch-contracts/src/main/resources/application.properties
  swatch-contracts/src/test/java/com/redhat/swatch/contract/config/DebugClientLoggerTest.java
Labels: QE Unneeded, Dev/approved

#4529 SWATCH-3586: when sync offering, increase timeout to handle messages plus metrics in the Product API rest client
  buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
  clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductService.java
  clients/quarkus/product-client/src/test/java/com/redhat/swatch/clients/product/ProductServiceTest.java
  swatch-contracts/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4559 SWATCH-2820: Remove k8s repo from database migrations
  swatch-database/src/main/docker/Dockerfile.jvm
Labels: Dev

#4565 SWATCH-2820: Update database fallback name
  swatch-database/deploy/clowdapp.yaml
Labels: Dev

#4530 WIP SWATCH-3532 Enable local testing for wiremock profile
  docker-compose.yml
  nginx.conf
  swatch-billable-usage/src/main/resources/application.properties
Labels: Dev/approved, QE/approved
