Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-01, with the labels that each got.

#4011 Add instructions for the use of the IQE to Ephemeral proxy
  docs/iqe-ee-proxy.md
Labels: Dev/approved, QE/approved

#4072 Fix build to work in any location and timezone
  swatch-common-export/src/main/java/com/redhat/swatch/export/utils/FileUtils.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Labels: QE Unneeded, Dev/approved

#4084 SWATCH-3167: Remove unused tables
  src/main/resources/liquibase/202501081035-remove-backup-tables.xml
  src/main/resources/liquibase/changelog.xml
Labels: QE Unneeded, Dev/approved

#4093 Clean up configuration for Quarkus services in tests
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/InMemoryMessageBrokerKafkaResource.java
  swatch-metrics/src/main/resources/application.yaml
  swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMetricsTaskManagerTest.java
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/configuration/Channels.java
  swatch-producer-aws/src/main/resources/application.properties
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/BillableUsageStatusProducerTest.java
  swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/resources/InMemoryMessageBrokerKafkaResource.java
  swatch-producer-azure/src/main/resources/application.properties
  swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageStatusProducerTest.java
Labels: Dev

#4090 CI: Add isolated job to validate format in GitHub actions
  .github/workflows/pr.yaml
  docker-compose.yml
Labels: QE Unneeded, Dev

#4094 Move swatchdog
  .gitignore
  poetry.lock
  pyproject.toml
  swatchdog/Makefile
  swatchdog/README.md
  swatchdog/setup.cfg
  swatchdog/swatchdog/__init__.py
  swatchdog/swatchdog/cli.py
  swatchdog/swatchdog/deploy/__init__.py
  swatchdog/swatchdog/deploy/command.py
  swatchdog/swatchdog/prometheus/__init__.py
  swatchdog/swatchdog/prometheus/command.py
  swatchdog/swatchdog/prometheus/data_writer.py
  swatchdog/tests/__init__.py
Labels: QE Unneeded, Dev/approved

#4081 SWATCH-3211: Ignore failures when consuming tally summary messages
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageMapper.java
  swatch-billable-usage/src/main/resources/application.properties
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageMapperTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/TallySummaryMessageConsumerTest.java
Labels: Dev/approved, QE/approved

#4104 SWATCH-3152: Configure swatch-producer-azure to skip bad messages
  swatch-producer-azure/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#4033 SWATCH-3177 Fix invalid remittance calculation when an amendment is applied
  src/main/resources/liquibase/202412091327-drop-hardware-measurement-type-from-billable-usage-remittance.xml
  src/main/resources/liquibase/changelog.xml
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceEntity.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceFilter.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceSummaryProjection.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageMapper.java
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepositoryTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageMapperTest.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
  swatch-core/schemas/billable_usage.yaml
  swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Labels: Dev/approved, QE/approved

#4115 SWATCH-3153: Configure swatch-producer-aws to skip bad messages
  swatch-producer-aws/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#4116 Configuration for SonarCloud rules
  .sonarlint/connectedMode.json
Labels: QE Unneeded, Dev/approved

#4124 Improve .gitignore
  .gitignore
Labels: Dev/approved

#4127 SWATCH-3247: Add missing "Managed-nodes" metric when exporting instances
  src/main/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperService.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperServiceTest.java
  src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
  swatch-core/schemas/instances_export_csv_item.yaml
  swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/MetricIdUtils.java
Labels: Dev/approved, QE/approved

#4139 Add test helper pods to iqe proxy
  bin/iqe-ee-proxy.sh
  docs/iqe-ee-proxy.md
  stub/wiremock.yaml
Labels: QE Unneeded, Dev/approved

#4138 SWATCH-3147: Configure swatch-producer-aws to use wiremock proxy in ephemeral
  swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsThrottlingException.java
  swatch-producer-aws/src/main/resources/application.properties
Labels: QE Unneeded, Dev/approved

#4145 SWATCH-3147: Do not overwrite aws marketplace properties in EE
  swatch-producer-aws/deploy/clowdapp.yaml
  swatch-producer-aws/src/main/resources/application.properties
Labels: Dev/approved

#4146 SWATCH-3267: Disable UMB in swatch-contracts in ephemeral environment
  deploy_ephemeral_env.sh
  swatch-contracts/src/main/resources/application.properties
Labels: Dev/approved
