Repository RedHatInsights/rhsm-subscriptions, pull requests merged in 2025-02, with the labels that each got.

#4108 SWATCH-3141: Configure swatch-billable-usage to skip bad messages
  swatch-billable-usage/src/main/resources/application.properties
Labels: Dev/approved, QE/approved

#4148 SWATCH-3267: Re-enable UMB in ephemeral
  swatch-contracts/src/main/resources/application.properties
Labels: Dev

#4151 SWATCH-3280: Add a comment including the tests image
  bin/delete_comment_iqe_summary.sh
  bin/post_comment_iqe_summary.sh
  pr_check.sh
Labels: QE Unneeded, Dev/approved

#4157 SWATCH-3294: Rename "swatch_billable_usage_total" to aggregated
  swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
  swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
Labels: QE Unneeded, Dev/approved

#4174 Improve logging when we receive event
  src/main/java/org/candlepin/subscriptions/event/EventController.java
Labels: QE Unneeded, Dev

#4158 SWATCH-2306: Create grafana dashboard for PAYG metrics
  .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Labels: QE Unneeded, Dev

#4193 Add more information in post result comment
  bin/post_comment_iqe_summary.sh
Labels: QE Unneeded, Dev/approved

#4192 SWATCH-2298: Remove the product-api (client) module for Spring
  build.gradle
  clients/build.gradle
  clients/product-client/product-client-config.json
  clients/quarkus/product-client/product-api-spec.yaml
  settings.gradle
  src/main/java/org/candlepin/subscriptions/capacity/files/ProductDenylist.java
  src/main/java/org/candlepin/subscriptions/product/ProductApiFactory.java
  src/main/java/org/candlepin/subscriptions/product/ProductConfiguration.java
  src/main/java/org/candlepin/subscriptions/product/ProductDataSource.java
  src/main/java/org/candlepin/subscriptions/product/ProductService.java
  src/main/java/org/candlepin/subscriptions/product/StubProductApi.java
  src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
  src/test/java/org/candlepin/subscriptions/files/ProductDenylistTest.java
  src/test/java/org/candlepin/subscriptions/product/ProductServiceTest.java
Labels: QE Unneeded, Dev

#4213 SWATCH-3217: CI: Configure Jenkins to use the upshift cloud
  Jenkinsfile
Labels: QE Unneeded, Dev/approved

#4188 SWATCH-2536 Subscription doesn't show if sku socket limit is unlimited
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
Labels: Dev/approved, QE/approved

#4224 Update the Subscription Watch - PAYG metrics Grafana dashboard to make the interval configurable
  .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Labels: Dev/approved

#4223 SWATCH-2133: Add test-snapshot-component task definition
  .tekton/verify-snapshot-components-pipeline.yaml
  .tekton/verify-snapshot-components-task.yaml
Labels: QE Unneeded, Dev/approved

#4220 SWATCH-2536 Subscription doesn't show if sku socket limit is unlimited
  src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
  swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
  swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
  swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
Labels: Dev/approved, QE/approved
